version: "3.9"

services:
  grafana:
    image: "grafana/grafana-oss:10.1.6"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped    
    container_name: "grafana"
    networks:
      - net
      #- db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.${HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.grafanasts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.grafanasts.headers.stspreload=true"
      - "traefik.http.middlewares.grafanasts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.grafanasts.headers.isdevelopment=false"
      - "traefik.http.routers.grafana.middlewares=grafanasts"
    volumes:
      - "grafana_data:/var/lib/grafana"
    environment:
      - TZ=Europe/Berlin

networks:
  net:
    external:
      name: traefik_net
  #db:

volumes:
  grafana_data:
