version: "3.9"

services:
  grafana:
    image: "grafana/grafana-oss"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: "grafana"
    networks:
      - net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.qxf.de`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    volumes:
      - "grafana_data:/var/lib/grafana"

networks:
  net:
    external:
      name: traefik_net

volumes:
  grafana_data:
